### ISSUE TITLE
VCT log should use canonicalized JSON when storing in Merkle tree 

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/vct#121]
Currently, when storing the verifiable credential into the Merkle tree, the "proof" field of the VC is removed and then the VC is marshalled using the standard JSON marshaller. The marshalled JSON still includes the context fields from the proof section even though they are no longer relevant. Later, verification may fail since the new VC potentially contains additional contexts from additional proofs. The VC should be marshalled into a canonical form (after the proofs are removed) before it is added to the Merkle tree. This will result in the exact same value every time, since the contexts from the proofs will not be included.

**Comment by troyronda** [comment]
This should be sorted out. We should be dealing with canonical forms.
